# Please do not change this query
# Its purpose is to find all of the locally referenced CSVs on which the RDF output
# of a CSV-W is dependent.

SELECT DISTINCT (str(?url) as ?csv) 
WHERE { 
    ?table <http://www.w3.org/ns/csvw#url> ?url.
    FILTER NOT EXISTS {
        ?table <http://www.w3.org/ns/csvw#suppressOutput> true.
    }

    # We don't want remote ones.
    FILTER(!regex(STR(?table), "^https?://", "i")).
}